In [53]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 400000

In [32]:
df = pd.read_csv("dataset.csv")

In [33]:
df

,woodSlot0,woodSlot1,woodSlot2,claySlot0,claySlot1,claySlot2,stoneSlot0,stoneSlot1,stoneSlot2,goldSlot0,...,card3resource1,card3resource2,card3resource3,height0,height1,height2,height3,moveSlot,moveAmount,fitness
0,0,0,0,0,0,0,0,0,0,0,...,2,0,1,4,4,4,4,clay,1,-16.333333
1,0,0,0,1,0,0,0,5,0,0,...,2,0,1,4,4,4,4,card2,1,-16.333333
2,0,0,2,1,0,0,0,5,0,0,...,2,0,1,4,4,4,4,stone,1,-16.333333
3,0,0,2,1,0,0,1,5,0,0,...,2,0,1,4,4,4,4,card1,1,-16.333333
4,0,0,2,1,0,1,1,5,0,0,...,2,0,1,4,4,4,4,prod,1,-16.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11296,0,0,0,0,0,0,1,5,0,0,...,0,2,1,3,2,1,2,gold,2,10.333333
11297,0,0,0,0,0,0,1,5,0,2,...,0,2,1,3,2,1,2,food,2,10.333333
11298,0,0,0,0,0,0,0,0,2,0,...,0,2,1,2,2,1,2,card2,1,10.333333
11299,0,0,0,0,0,0,0,0,2,0,...,0,2,1,2,2,1,2,clay,3,10.333333
11300,0,0,0,3,0,0,0,0,2,0,...,0,2,1,2,2,1,2,stone,3,10.333333

In [31]:
sum(list(df["woodSlot0"]))

0

In [22]:
df.columns

Index(['woodSlot0', 'woodSlot1', 'woodSlot2', 'claySlot0', 'claySlot1',
       'claySlot2', 'stoneSlot0', 'stoneSlot1', 'stoneSlot2', 'goldSlot0',
       'goldSlot1', 'goldSlot2', 'foodSlot0', 'foodSlot1', 'foodSlot2',
       'tentSlot0', 'tentSlot1', 'tentSlot2', 'card1Slot0', 'card1Slot1',
       'card1Slot2', 'card2Slot0', 'card2Slot1', 'card2Slot2', 'card3Slot0',
       'card3Slot1', 'card3Slot2', 'card4Slot0', 'card4Slot1', 'card4Slot2',
       'prodSlot0', 'prodSlot1', 'prodSlot2', 'wood0', 'wood1', 'wood2',
       'clay0', 'clay1', 'clay2', 'stone0', 'stone1', 'stone2', 'gold0',
       'gold1', 'gold2', 'food0', 'food1', 'food2', 'maxMeeples0',
       'maxMeeples1', 'maxMeeples2', 'prod0', 'prod1', 'prod2', 'points0',
       'points1', 'points2', 'card0resource0', 'card0resource1',
       'card0resource2', 'card0resource3', 'card1resource0', 'card1resource1',
       'card1resource2', 'card1resource3', 'card2resource0', 'card2resource1',
       'card2resource2', 'card2resource3', 'card3resource0', 'card3resource1',
       'card3resource2', 'card3resource3', 'height0', 'height1', 'height2',
       'height3', 'moveSlot', 'moveAmount', 'fitness'],
      dtype='object')

In [34]:
df.corr()

,woodSlot0,woodSlot1,woodSlot2,claySlot0,claySlot1,claySlot2,stoneSlot0,stoneSlot1,stoneSlot2,goldSlot0,...,card3resource0,card3resource1,card3resource2,card3resource3,height0,height1,height2,height3,moveAmount,fitness
woodSlot0,1.000000,0.020583,0.006359,-0.038433,0.057625,0.038048,-0.056130,0.050639,0.031377,-0.037813,...,0.005183,-0.006267,-0.013847,0.021580,-0.023301,-0.021940,-0.016488,-0.027426,-0.122318,0.008841
woodSlot1,0.020583,1.000000,-0.025152,0.062566,-0.082995,0.031748,0.014372,-0.085476,0.048666,0.072904,...,0.009436,-0.020019,-0.013785,0.036150,-0.017773,-0.033598,0.004155,-0.028291,-0.066800,0.026398
woodSlot2,0.006359,-0.025152,1.000000,0.025030,0.065771,-0.090601,0.024976,0.032045,-0.110779,0.067095,...,0.013862,-0.009755,-0.003280,-0.000441,-0.003580,-0.014462,0.019501,-0.009826,-0.044341,-0.017340
claySlot0,-0.038433,0.062566,0.025030,1.000000,0.001739,0.010393,-0.035416,0.048357,0.030867,-0.044156,...,-0.027910,0.017862,0.010984,-0.002609,-0.013840,-0.041919,-0.058948,-0.019478,-0.107188,-0.042423
claySlot1,0.057625,-0.082995,0.065771,0.001739,1.000000,-0.028360,0.047414,-0.070728,0.063483,0.048422,...,-0.020479,0.025084,0.001319,-0.010455,-0.010753,-0.018558,-0.041321,-0.026491,-0.063363,0.011172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
height1,-0.021940,-0.033598,-0.014462,-0.041919,-0.018558,-0.016341,-0.032007,-0.028084,-0.041435,-0.032078,...,0.005441,0.044590,-0.037460,-0.022113,0.462270,1.000000,0.492061,0.489646,-0.041876,-0.006431
height2,-0.016488,0.004155,0.019501,-0.058948,-0.041321,-0.053555,-0.013769,-0.039824,-0.024970,-0.043307,...,0.063846,-0.031053,-0.020760,-0.014965,0.437071,0.492061,1.000000,0.426336,-0.034847,-0.002764
height3,-0.027426,-0.028291,-0.009826,-0.019478,-0.026491,-0.015066,-0.028969,-0.031812,-0.057018,-0.021789,...,-0.030525,0.023341,0.039803,-0.047777,0.386321,0.489646,0.426336,1.000000,-0.034227,-0.000525
moveAmount,-0.122318,-0.066800,-0.044341,-0.107188,-0.063363,-0.064310,-0.113600,-0.064226,-0.063586,-0.122074,...,-0.008326,0.002792,0.005177,0.000363,-0.042087,-0.041876,-0.034847,-0.034227,1.000000,-0.011915
fitness,0.008841,0.026398,-0.017340,-0.042423,0.011172,0.010529,-0.011661,0.001681,0.029067,-0.001903,...,-0.000604,-0.006287,0.006702,0.000881,-0.002862,-0.006431,-0.002764,-0.000525,-0.011915,1.000000

In [48]:
cors = df.corr().abs()
cors.values[np.triu_indices_from(cors, 0)] = np.nan
cors = cors.unstack()
cors = cors.sort_values(na_position="first")

In [58]:
df.corr()["fitness"].abs().sort_values()

tentSlot1         0.000429
height3           0.000525
card3resource0    0.000604
card3resource3    0.000881
wood1             0.000906
card1resource3    0.001397
stoneSlot1        0.001681
goldSlot0         0.001903
card0resource2    0.002103
height2           0.002764
card2Slot2        0.002767
height0           0.002862
stone0            0.003248
card0resource0    0.004219
card1resource2    0.004608
card2resource1    0.004912
maxMeeples1       0.005415
card1resource0    0.005891
card0resource1    0.006258
card2Slot0        0.006260
card3resource1    0.006287
height1           0.006431
card0resource3    0.006700
card3resource2    0.006702
card2Slot1        0.007066
maxMeeples2       0.008138
card1Slot2        0.008668
woodSlot0         0.008841
card2resource3    0.008999
card2resource2    0.009308
card2resource0    0.009426
card4Slot0        0.009679
card3Slot2        0.009744
claySlot2         0.010529
card1resource1    0.010930
claySlot1         0.011172
stoneSlot0        0.011661
moveAmount        0.011915
card4Slot2        0.013162
card1Slot1        0.013565
prodSlot2         0.015653
card1Slot0        0.016119
goldSlot2         0.017313
woodSlot2         0.017340
maxMeeples0       0.017359
wood0             0.020532
card3Slot0        0.020587
tentSlot0         0.022965
tentSlot2         0.024906
foodSlot2         0.026263
woodSlot1         0.026398
foodSlot1         0.027168
wood2             0.027383
card3Slot1        0.027747
goldSlot1         0.027955
clay1             0.028640
stoneSlot2        0.029067
clay2             0.030935
claySlot0         0.042423
prodSlot0         0.043449
card4Slot1        0.043884
foodSlot0         0.043944
food1             0.053729
clay0             0.054954
gold1             0.056860
prodSlot1         0.057536
food2             0.058990
stone1            0.060474
prod2             0.069183
stone2            0.079101
gold2             0.107636
points1           0.117142
food0             0.120094
prod1             0.134511
gold0             0.154210
points2           0.163174
prod0             0.197496
points0           0.282247
fitness           1.000000
Name: fitness, dtype: float64

,woodSlot0,woodSlot1,woodSlot2,claySlot0,claySlot1,claySlot2,stoneSlot0,stoneSlot1,stoneSlot2,goldSlot0,...,card3resource1,card3resource2,card3resource3,height0,height1,height2,height3,moveSlot,moveAmount,fitness
0,0,0,0,0,0,0,0,0,0,0,...,2,1,0,4,4,4,4,food,2,-32.666667
1,0,0,0,0,0,0,0,0,0,0,...,2,1,0,4,4,4,4,tent,2,-32.666667
2,0,0,0,0,0,0,0,0,0,0,...,2,1,0,4,4,4,4,card4,1,-32.666667
3,0,0,0,0,0,0,0,0,0,0,...,2,1,0,4,4,4,4,tent,1,-32.666667
4,0,0,0,0,0,0,0,0,0,0,...,2,1,0,4,4,4,4,clay,5,-32.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11604,0,0,0,0,0,0,0,0,0,0,...,1,0,1,3,4,1,2,clay,4,45.000000
11605,0,0,0,0,0,0,0,0,0,0,...,1,0,1,3,4,1,2,gold,1,45.000000
11606,0,0,0,0,0,0,0,0,0,0,...,1,0,1,2,4,1,2,stone,4,45.000000
11607,0,0,0,0,0,0,0,0,0,0,...,1,0,1,2,4,1,2,card3,1,45.000000
11608,0,0,0,0,0,0,0,0,0,0,...,1,0,1,2,4,1,2,food,2,45.000000